[kafka.producer.server]
    bootstrap_servers = "localhost:9092"
    client_id = "rt-yse-server-producer-1"
    acks = "all"

[kafka.consumer.yahoo_search]
    bootstrap_servers = "localhost:9092"
    enable_auto_commit = false
    client_id = "rt-yse-search-consumer-1"
    group_id = "rt-yse-search-consumer-1"
    auto_offset_reset = "earliest"

[kafka.producer.yahoo_search]
    bootstrap_servers = "localhost:9092"
    client_id = "rt-yse-search-producer-1"
    acks = "all"

[kafka.consumer.extractor]
    bootstrap_servers = "localhost:9092"
    enable_auto_commit = false
    client_id = "rt-yse-extractor-consumer-1"
    group_id = "rt-yse-extractor-consumer-1"
    auto_offset_reset = "earliest"

[postgres]
    connection_string = "postgresql+asyncpg:///yahoo_search_engine_rt"